global using MediatR;
global using Microsoft.AspNetCore.Mvc;
global using Pic.Core.Infrastructure.Models;
global using Pic.Core.Logic.PhotoAlbums.Commands;
global using Pic.Core.Logic.PhotoAlbums.Queries;
global using Pic.Core.Logic.Photos.Commands;
global using Pic.Core.Logic.Photos.Queries;
global using Pic.Service.Areas.PhotoAlbums.Models;
global using Pic.Service.Areas.Photos.Models;
global using Mapper = Pic.Core.Shared.Extensions.Mapper;
